// sort-imports-ignore
import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components';
import { Providers } from './_providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

const LocaleLayout = ({
  children,
  params: { locale },
}: Readonly<LocaleLayoutProps>) => {
  return (
    <html lang={locale}>
      <Providers locale={locale}>
        <body className={inter.className}>
          <Header />
          <main>{children}</main>
        </body>
      </Providers>
    </html>
  );
};

export default LocaleLayout;
